name: cpp-linter

# Triggers the workflow on push or pull request events
on:
  push:
  pull_request:
jobs:
  cpp-linter:
    name: cpp-linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: C/C++ Lint Action
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: shenxianpeng/cpp-linter-action@master-py
        with:
          style: 'google'
          version: '11'
          diff-only: ture
          verbosity: '10'