name: cpp-linter

# Workflow syntax:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

# Triggers the workflow on push or pull request events
on:
  push:
  pull_request:
    types: [opened]
    
jobs:
  cpp-linter:
    name: cpp-linter
    runs-on: ubuntu-latest
    steps:
      # Checkout the code base
      - name: Checkout code
        uses: actions/checkout@v2
      # Run linter against code base
      - name: Lint code
        uses: shenxianpeng/cpp-linter-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'google'
          files-changed-only: true
          version: '12'
          diff-only: true
          verbosity: '10'
          gnore: .|!demo.cpp|!demo.hpp
          thread-comments: true
      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: |
          echo "Some files failed the linting checks!"
