name: cpp-linter as action

on:
  workflow_dispatch:
  workflow_call:


jobs:
  pre-seed-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.extract-version-range.outputs.versions }}
    steps:
      - env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release download
          -R cpp-linter/clang-tools-static-binaries
          --pattern versions.json
          --output versions.json
      - name: Extract version range
        id: extract-version-range
        shell: python
        run: |-
          import json
          from os import environ
          from pathlib import Path
          content = Path("versions.json").read_text(encoding="utf-8")
          metadata = json.loads(content)
          versions = list(metadata["llvm_versions"].keys())
          versions.sort()
          with open(environ["GITHUB_OUTPUT"], mode="a") as gh_out:
              gh_out.write(f"versions={json.dumps(versions)}\n")

  test:
    needs: pre-seed-versions
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        clang-version: ${{ fromJSON(needs.pre-seed-versions.outputs.versions) }}
      fail-fast: false

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.os == 'ubuntu-latest' && 'ubuntu:latest' || '' }}
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
          submodules: ${{ matrix.os != 'ubuntu-latest' }}
          repository: cpp-linter/test-cpp-linter-action

      - name: Cache the build artifacts
        id: cache-build
        uses: actions/cache@v6
        with:
          path: build
          key: ${{ runner.os }}-${{ hashFiles('src/CMakeLists.txt', 'src/demo.cpp', 'src/demo.hpp') }}

      - name: Install necessary Linux tools
        if: matrix.os == 'ubuntu-latest'
        run: >-
          apt-get update &&
          apt-get install -y libc6 cmake gcc g++ wget lsb-release
      - name: Generate compilation database
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: mkdir build && cmake -Bbuild src

      - name: Run linter as action
        uses: cpp-linter/cpp-linter-action@main
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          files-changed-only: false
          # to ignore all build folder contents
          ignore: build
          database: build
          verbosity: debug
          version: ${{ matrix.clang-version }}
          thread-comments: ${{ matrix.clang-version == '17' && 'update' }}
          file-annotations: ${{ matrix.clang-version == '17' }}
          extra-args: -std=c++14 -Wall

      - name: Fail fast?!
        # if: steps.linter.outputs.checks-failed > 0
        run: |
          echo "some linter checks failed"
          echo "total: ${{ steps.linter.outputs.checks-failed }}"
          echo "clang-format: ${{ steps.linter.outputs.clang-format-checks-failed }}"
          echo "clang-tidy: ${{ steps.linter.outputs.clang-tidy-checks-failed }}"
        # for actual deployment
        # run: exit 1
